import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: "Dashboard",
    logistics: "District Logistics",
    daily_ops: "Daily Operations",
    surveillance: "Surveillance",
    command_center: "Command Center",
    attendance: "Staff Attendance",
    patient_logging: "Patient Logging",
    registry: "Admin Registry",
    public_portal: "Public Portal",
    sign_out: "Sign Out",
    sos: "SOS",
    ai_assistant: "AI Assistant",
    live_system: "Live System",
    location_filter: "Location Filter",
    all_districts: "All Districts (Default)",
    total_phcs: "Total PHCs",
    patients_today: "Patients Today",
    available_beds: "Available Beds",
    medicine_stock: "Medicine Stock",
    district_facilities: "District Facilities",
    district_overview_analytics: "District Overview & Analytics",
    formal_report: "Formal Report",
    redistribution_engine: "Redistribution Engine",
    surveillance_grid: "Disease Surveillance Grid",
    command_alerts: "Command Center Alerts",
    analyzing_district: "Analyzing District...",
    ai_pulse_check: "AI Pulse Check",
    ai_insight: "AI Insight",
    avg_footfall: "Avg Footfall",
    total_beds: "Total Beds",
    recent_district_logs: "Recent District Logs",
    used: "Used",
    units: "units",
    reported: "Reported",
    cases: "cases",
    defect: "Defect",
    multi_agency_command_center: "Multi-Agency Command Center",
    emergency_routing_dispatch_hub: "Emergency Routing & Dispatch Hub",
    police_department: "Police Department",
    disaster_management: "Disaster Management",
    water_department: "Water Department",
    state_health_ministry: "State Health Ministry",
    refresh_feed: "Refresh Feed",
    scanning_frequencies: "Scanning frequencies...",
    no_active_alerts: "No active alerts in the district.",
    severity: "Severity",
    origin: "Origin",
    dispatched_to: "Dispatched to",
    broadcast_alert: "Broadcast Alert",
    live_infection_tracking: "Live Infection Tracking & Risk Monitoring",
    aggregating_logs: "Aggregating Daily Logs...",
    risk_tier: "Risk Tier",
    risk: "RISK",
    total_active_cases: "Total Active Cases",
    citizen_health_portal: "Citizen Health Portal",
    search: "Search",
    search_placeholder: "Search your district (e.g. 'Kaveri District', 'Surya Nagar')...",
    facilities_found: "Facilities found for",
    scanning_network: "Scanning network...",
    no_facilities_found: "No facilities found in this region.",
    total_bed_capacity: "Total Bed Capacity",
    recent_alerts: "Recent Alerts",
    warnings: "Warnings",
    none_active: "None active.",
    ambulance_dispatch: "Ambulance Dispatch",
    vehicle_identifier: "Vehicle Identifier",
    operational_status: "Operational Status",
    fuel_level: "Fuel Level",
    driver_contact: "Driver Contact",
    live_tracking: "Live Tracking",
    mock_gps: "Mock GPS Coordinates",
    project_roadmap: "Project Roadmap",
    vision_title: "ArogyaNet: The Future Roadmap",
    vision_subtitle: "Welcome to the future of District Health Command.",
    phase_1: "Phase 1: Real-time Command",
    phase_1_desc: "ArogyaNet currently provides real-time logistics, AI-powered predictive redistribution, and an open command center.",
    phase_2: "Phase 2: IoT & Live Sensor Integration",
    phase_2_desc: "Automated Inventory Ping & Cold Chain Tracking with real-time temperature sensors.",
    phase_3: "Phase 3: Drone Delivery Network",
    phase_3_desc: "Autonomous drones carrying critical supplies dispatched directly from the Command Center.",
    phase_4: "Phase 4: Blockchain & Decentralized Identity",
    phase_4_desc: "Secure, immutable ledger for patient history and cryptographic verification of pharmaceuticals.",
    recent_pathogen_logs: "Recent Pathogen Logs",
    operating_status: "Operating Status",
    fully_operational: "Fully Operational",
    public_bed_capacity: "Public Bed Capacity",
    ambulance_fleet_status: "Ambulance Fleet Status",
    active: "Active",
    beds: "Beds",
    restricted_message: "Detailed logistics and staff attendance are restricted to District Administrators.",
    no_recent_disease_logs: "No recent disease logs.",
    status: "Status",
    staff_shortage: "Staff Shortage",
    normal: "Normal",
    elevated: "Elevated",
    high: "High"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    logistics: "ज़िला रसद",
    daily_ops: "दैनिक संचालन",
    surveillance: "निगरानी",
    command_center: "कमांड सेंटर",
    attendance: "कर्मचारी उपस्थिति",
    patient_logging: "मरीज़ लॉगिंग",
    registry: "व्यवस्थापक रजिस्ट्री",
    public_portal: "सार्वजनिक पोर्टल",
    sign_out: "साइन आउट",
    sos: "एसओएस (आपातकाल)",
    ai_assistant: "एआई सहायक",
    live_system: "लाइव सिस्टम",
    location_filter: "स्थान फ़िल्टर",
    all_districts: "सभी ज़िले (डिफ़ॉल्ट)",
    total_phcs: "कुल PHC",
    patients_today: "आज के मरीज",
    available_beds: "उपलब्ध बिस्तर",
    medicine_stock: "दवा का स्टॉक",
    district_facilities: "ज़िला सुविधाएँ",
    district_overview_analytics: "ज़िला अवलोकन और एनालिटिक्स",
    formal_report: "औपचारिक रिपोर्ट",
    redistribution_engine: "पुनर्वितरण इंजन",
    surveillance_grid: "रोग निगरानी ग्रिड",
    command_alerts: "कमांड सेंटर अलर्ट",
    analyzing_district: "ज़िले का विश्लेषण हो रहा है...",
    ai_pulse_check: "एआई पल्स चेक",
    ai_insight: "एआई इनसाइट",
    avg_footfall: "औसत पदयात्रा",
    total_beds: "कुल बिस्तर",
    recent_district_logs: "हाल के ज़िला लॉग",
    used: "उपयोग किया गया",
    units: "इकाइयाँ",
    reported: "रिपोर्ट किया गया",
    cases: "मामले",
    defect: "खराबी",
    multi_agency_command_center: "बहु-एजेंसी कमांड सेंटर",
    emergency_routing_dispatch_hub: "आपातकालीन रूटिंग और प्रेषण हब",
    police_department: "पुलिस विभाग",
    disaster_management: "आपदा प्रबंधन",
    water_department: "जल विभाग",
    state_health_ministry: "राज्य स्वास्थ्य मंत्रालय",
    refresh_feed: "फ़ीड ताज़ा करें",
    scanning_frequencies: "फ्रीक्वेंसी स्कैन की जा रही है...",
    no_active_alerts: "जिले में कोई सक्रिय अलर्ट नहीं।",
    severity: "गंभीरता",
    origin: "मूल",
    dispatched_to: "को भेजा गया",
    broadcast_alert: "अलर्ट प्रसारित करें",
    live_infection_tracking: "लाइव संक्रमण ट्रैकिंग और जोखिम निगरानी",
    aggregating_logs: "दैनिक लॉग एकत्र किए जा रहे हैं...",
    risk_tier: "जोखिम स्तर",
    risk: "जोखिम",
    total_active_cases: "कुल सक्रिय मामले",
    high: "उच्च",
    citizen_health_portal: "नागरिक स्वास्थ्य पोर्टल",
    search: "खोज",
    search_placeholder: "अपने जिले में खोजें (उदा. 'कावेरी जिला', 'सूर्य नगर')...",
    facilities_found: "के लिए मिली सुविधाएं",
    scanning_network: "नेटवर्क स्कैन हो रहा है...",
    no_facilities_found: "इस क्षेत्र में कोई सुविधाएं नहीं मिलीं।",
    total_bed_capacity: "कुल बिस्तर क्षमता",
    recent_alerts: "हाल के अलर्ट",
    warnings: "चेतावनियाँ",
    none_active: "कोई सक्रिय नहीं।",
    ambulance_dispatch: "एम्बुलेंस प्रेषण",
    vehicle_identifier: "वाहन पहचानकर्ता",
    operational_status: "परिचालन स्थिति",
    fuel_level: "ईंधन स्तर",
    driver_contact: "ड्राइवर संपर्क",
    live_tracking: "लाइव ट्रैकिंग",
    mock_gps: "मॉक जीपीएस निर्देशांक",
    project_roadmap: "प्रोजेक्ट रोडमैप",
    vision_title: "आरोग्यनेट: भविष्य का रोडमैप",
    vision_subtitle: "जिला स्वास्थ्य कमान के भविष्य में आपका स्वागत है।",
    phase_1: "चरण 1: रीयल-टाइम कमांड",
    phase_1_desc: "आरोग्यनेट वर्तमान में रीयल-टाइम लॉजिस्टिक्स, एआई-संचालित भविष्य कहनेवाला पुनर्वितरण और एक खुला कमांड सेंटर प्रदान करता है।",
    phase_2: "चरण 2: IoT और लाइव सेंसर एकीकरण",
    phase_2_desc: "स्वचालित इन्वेंटरी पिंग और रीयल-टाइम तापमान सेंसर के साथ कोल्ड चेन ट्रैकिंग।",
    phase_3: "चरण 3: ड्रोन डिलीवरी नेटवर्क",
    phase_3_desc: "कमांड सेंटर से सीधे भेजे गए महत्वपूर्ण आपूर्ति ले जाने वाले स्वायत्त ड्रोन।",
    phase_4: "चरण 4: ब्लॉकचेन और विकेन्द्रीकृत पहचान",
    phase_4_desc: "रोगी के इतिहास के लिए सुरक्षित, अपरिवर्तनीय खाता बही और फार्मास्यूटिकल्स का क्रिप्टोग्राफिक सत्यापन।",
    recent_pathogen_logs: "हाल के रोगजनक लॉग",
    operating_status: "परिचालन स्थिति",
    fully_operational: "पूर्णतः चालू",
    public_bed_capacity: "सार्वजनिक बिस्तर क्षमता",
    ambulance_fleet_status: "एम्बुलेंस बेड़े की स्थिति",
    active: "सक्रिय",
    beds: "बिस्तर",
    restricted_message: "विस्तृत रसद और कर्मचारियों की उपस्थिति जिला प्रशासकों तक ही सीमित है।",
    no_recent_disease_logs: "कोई हालिया रोग लॉग नहीं।",
    status: "स्थिति",
    staff_shortage: "कर्मचारी कमी",
    normal: "सामान्य",
    elevated: "बढ़ा हुआ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // 'en' or 'hi'

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
