import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: "Dashboard",
    logistics: "District Logistics",
    daily_ops: "Daily Operations",
    surveillance: "Surveillance",
    command_center: "Command Center",
    attendance: "Staff Attendance",
    patient_logging: "Patient Logging",
    registry: "Admin Registry",
    public_portal: "Public Portal",
    sign_out: "Sign Out",
    sos: "SOS",
    ai_assistant: "AI Assistant",
    live_system: "Live System",
    location_filter: "Location Filter",
    all_districts: "All Districts (Default)",
    total_phcs: "Total PHCs",
    patients_today: "Patients Today",
    available_beds: "Available Beds",
    medicine_stock: "Medicine Stock",
    district_facilities: "District Facilities",
    district_overview_analytics: "District Overview & Analytics",
    formal_report: "Formal Report",
    redistribution_engine: "Redistribution Engine",
    surveillance_grid: "Disease Surveillance Grid",
    command_alerts: "Command Center Alerts",
    analyzing_district: "Analyzing District...",
    ai_pulse_check: "AI Pulse Check",
    ai_insight: "AI Insight",
    avg_footfall: "Avg Footfall",
    total_beds: "Total Beds",
    recent_district_logs: "Recent District Logs",
    used: "Used",
    units: "units",
    reported: "Reported",
    cases: "cases",
    defect: "Defect",
    multi_agency_command_center: "Multi-Agency Command Center",
    emergency_routing_dispatch_hub: "Emergency Routing & Dispatch Hub",
    police_department: "Police Department",
    disaster_management: "Disaster Management",
    water_department: "Water Department",
    state_health_ministry: "State Health Ministry",
    refresh_feed: "Refresh Feed",
    scanning_frequencies: "Scanning frequencies...",
    no_active_alerts: "No active alerts in the district.",
    severity: "Severity",
    origin: "Origin",
    dispatched_to: "Dispatched to",
    broadcast_alert: "Broadcast Alert",
    live_infection_tracking: "Live Infection Tracking & Risk Monitoring",
    aggregating_logs: "Aggregating Daily Logs...",
    risk_tier: "Risk Tier",
    risk: "RISK",
    total_active_cases: "Total Active Cases",
    citizen_health_portal: "Citizen Health Portal",
    search: "Search",
    search_placeholder: "Search your district (e.g. 'Kaveri District', 'Surya Nagar')...",
    facilities_found: "Facilities found for",
    scanning_network: "Scanning network...",
    no_facilities_found: "No facilities found in this region.",
    total_bed_capacity: "Total Bed Capacity",
    recent_alerts: "Recent Alerts",
    warnings: "Warnings",
    none_active: "None active.",
    ambulance_dispatch: "Ambulance Dispatch",
    vehicle_identifier: "Vehicle Identifier",
    operational_status: "Operational Status",
    fuel_level: "Fuel Level",
    driver_contact: "Driver Contact",
    live_tracking: "Live Tracking",
    mock_gps: "Mock GPS Coordinates",
    project_roadmap: "Project Roadmap",
    vision_title: "ArogyaNet: The Future Roadmap",
    vision_subtitle: "Welcome to the future of District Health Command.",
    phase_1: "Phase 1: Real-time Command",
    phase_1_desc: "ArogyaNet currently provides real-time logistics, AI-powered predictive redistribution, and an open command center.",
    phase_2: "Phase 2: IoT & Live Sensor Integration",
    phase_2_desc: "Automated Inventory Ping & Cold Chain Tracking with real-time temperature sensors.",
    phase_3: "Phase 3: Drone Delivery Network",
    phase_3_desc: "Autonomous drones carrying critical supplies dispatched directly from the Command Center.",
    phase_4: "Phase 4: Blockchain & Decentralized Identity",
    phase_4_desc: "Secure, immutable ledger for patient history and cryptographic verification of pharmaceuticals.",
    recent_pathogen_logs: "Recent Pathogen Logs",
    operating_status: "Operating Status",
    fully_operational: "Fully Operational",
    public_bed_capacity: "Public Bed Capacity",
    ambulance_fleet_status: "Ambulance Fleet Status",
    active: "Active",
    beds: "Beds",
    restricted_message: "Detailed logistics and staff attendance are restricted to District Administrators.",
    no_recent_disease_logs: "No recent disease logs.",
    status: "Status",
    staff_shortage: "Staff Shortage",
    normal: "Normal",
    elevated: "Elevated",
    high: "High",
    national_overview: "National Overview",
    state_insights: "State Insights",
    district_explorer: "District Explorer",
    india_health_infrastructure: "India Health Infrastructure",
    real_time_aggregated_data: "Real-time aggregated data from Government of India datasets",
    primary_health_centres: "Primary Health Centres",
    community_health_centres: "Community Health Centres",
    govt_doctors: "Govt. Doctors",
    licensed_blood_banks: "Licensed Blood Banks",
    infrastructure_breakdown: "Infrastructure Breakdown",
    top_states_phcs: "Top States by PHCs",
    top_states_doctors: "Top States by Doctors",
    top_states_blood_banks: "Top States by Blood Banks",
    state_col: "State",
    public_banks: "Public Banks",
    private_banks: "Private Banks",
    total: "Total",
    state_health_infrastructure: "State Health Infrastructure",
    select_state_map: "Select a state on the map to view detailed insights",
    select_state_dropdown: "Select a State to View Insights",
    profile: "Profile",
    state_workforce: "State Workforce",
    sanctioned_doctors: "Sanctioned Doctors",
    in_position: "In Position",
    shortfall: "Shortfall",
    district_infrastructure: "District Infrastructure Distribution",
    district: "District",
    awaiting_selection: "Awaiting selection. Click any state on the map.",
    // Public Portal New Strings
    home: "Home",
    national_data: "National Data",
    command_login: "Command Login",
    emergency_sos: "Emergency SOS",
    switch_hindi: "Switch to Hindi",
    switch_english: "Switch to English",
    system_status: "System Status: All Systems Operational",
    built_for_india: "Built for India.",
    
    hero_badge: "Official Public Portal",
    hero_title1: "India's AI-Powered",
    hero_title2: "Health Intelligence",
    hero_desc: "Bridging the gap between data and action. ArogyaNet AI unifies national datasets to provide real-time insights, predictive resource allocation, and citizen-first transparency.",
    explore_data: "Explore National Data",
    
    why_title: "Why ArogyaNet AI?",
    why_desc: "For decades, healthcare data has been siloed across thousands of districts. ArogyaNet AI acts as a central nervous system, bringing total visibility to infrastructure, workforce, and critical resources.",
    unified_data: "Unified Datasets",
    unified_data_desc: "Aggregating Open Government Data (OGD) into a single, high-performance PostgreSQL intelligence layer.",
    pred_analytics: "Predictive Analytics",
    pred_analytics_desc: "Forecasting medication shortages and infrastructure bottlenecks using advanced AI models.",
    cit_transparency: "Citizen Transparency",
    cit_transparency_desc: "Empowering everyday citizens to locate nearby facilities, blood banks, and specialized doctors.",
    
    dual_intel: "Dual-Targeted Intelligence",
    for_citizens: "For Citizens",
    cit_point1: "Locate the nearest operational PHCs and CHCs",
    cit_point2: "Check real-time availability of licensed blood banks",
    cit_point3: "View specialized doctor availability in your state",
    cit_point4: "Access disease advisories and emergency SOS",
    view_dashboard: "View Public Dashboard",
    // Contact Page
    contact_title: "Contact",
    contact_desc: "Have questions about the platform, datasets, or integration? Reach out to our team.",
    contact_form_title: "Send us a Message",
    contact_success: "Message sent successfully. Our team will get back to you shortly.",
    contact_error: "Failed to send message. Please try again later.",
    contact_signin_msg: "Please be signed in to send suggestions or contact the team.",
    contact_signin_btn: "Sign In",
    contact_name: "Name",
    contact_email: "Email",
    contact_phone: "Phone Number",
    contact_subject: "Subject",
    contact_message: "Message",
    contact_send_btn: "Send Message",
    contact_founder: "Founder",
    contact_founder_desc: "Building AI-powered healthcare intelligence solutions for India. Interested in collaboration? Reach out to collaborate.",
    contact_linkedin: "Connect on LinkedIn",
    
    // District Explorer
    explore_healthcare: "Explore Healthcare Infrastructure Near You",
    search_district: "Search your district...",
    featured_districts: "Featured Districts",
    search_results: "Search Results",
    no_districts_found: "No districts found.",
    district_profile: "Healthcare Infrastructure Profile",
    back_to_districts: "Back to Districts",
    infrastructure_distribution: "Infrastructure Distribution",
    
    for_govt: "For Government",
    gov_point1: "Analyze state-wise historical growth trends",
    gov_point2: "Monitor real-time inventory and logistics",
    gov_point3: "Track disease outbreaks via the Surveillance Module",
    gov_point4: "AI-driven staff attendance and footprint predictions",
    access_command: "Access Command Center",
    
    future_roadmap: "National Expansion Roadmap",
    future_roadmap_desc: "We are actively integrating massive central datasets to expand our intelligence capabilities.",
    coming_phase2: "Coming Phase 2",
    aqi_heatwave: "AQI & Heatwave Alerts",
    maternal_child: "Maternal & Child Health",
    vaccination_intel: "Vaccination Intelligence",
    census_pop: "Census & Population",

  },
  hi: {
    dashboard: "डैशबोर्ड",
    logistics: "ज़िला रसद",
    daily_ops: "दैनिक संचालन",
    surveillance: "निगरानी",
    command_center: "कमांड सेंटर",
    attendance: "कर्मचारी उपस्थिति",
    patient_logging: "मरीज़ लॉगिंग",
    registry: "व्यवस्थापक रजिस्ट्री",
    public_portal: "सार्वजनिक पोर्टल",
    sign_out: "साइन आउट",
    sos: "एसओएस (आपातकाल)",
    ai_assistant: "एआई सहायक",
    live_system: "लाइव सिस्टम",
    location_filter: "स्थान फ़िल्टर",
    all_districts: "सभी ज़िले (डिफ़ॉल्ट)",
    total_phcs: "कुल PHC",
    patients_today: "आज के मरीज",
    available_beds: "उपलब्ध बिस्तर",
    medicine_stock: "दवा का स्टॉक",
    district_facilities: "ज़िला सुविधाएँ",
    district_overview_analytics: "ज़िला अवलोकन और एनालिटिक्स",
    formal_report: "औपचारिक रिपोर्ट",
    redistribution_engine: "पुनर्वितरण इंजन",
    surveillance_grid: "रोग निगरानी ग्रिड",
    command_alerts: "कमांड सेंटर अलर्ट",
    analyzing_district: "ज़िले का विश्लेषण हो रहा है...",
    ai_pulse_check: "एआई पल्स चेक",
    ai_insight: "एआई इनसाइट",
    avg_footfall: "औसत पदयात्रा",
    total_beds: "कुल बिस्तर",
    recent_district_logs: "हाल के ज़िला लॉग",
    used: "उपयोग किया गया",
    units: "इकाइयाँ",
    reported: "रिपोर्ट किया गया",
    cases: "मामले",
    defect: "खराबी",
    multi_agency_command_center: "बहु-एजेंसी कमांड सेंटर",
    emergency_routing_dispatch_hub: "आपातकालीन रूटिंग और प्रेषण हब",
    police_department: "पुलिस विभाग",
    disaster_management: "आपदा प्रबंधन",
    water_department: "जल विभाग",
    state_health_ministry: "राज्य स्वास्थ्य मंत्रालय",
    refresh_feed: "फ़ीड ताज़ा करें",
    scanning_frequencies: "फ्रीक्वेंसी स्कैन की जा रही है...",
    no_active_alerts: "जिले में कोई सक्रिय अलर्ट नहीं।",
    severity: "गंभीरता",
    origin: "मूल",
    dispatched_to: "को भेजा गया",
    broadcast_alert: "अलर्ट प्रसारित करें",
    live_infection_tracking: "लाइव संक्रमण ट्रैकिंग और जोखिम निगरानी",
    aggregating_logs: "दैनिक लॉग एकत्र किए जा रहे हैं...",
    risk_tier: "जोखिम स्तर",
    risk: "जोखिम",
    total_active_cases: "कुल सक्रिय मामले",
    high: "उच्च",
    citizen_health_portal: "नागरिक स्वास्थ्य पोर्टल",
    search: "खोज",
    search_placeholder: "अपने जिले में खोजें (उदा. 'कावेरी जिला', 'सूर्य नगर')...",
    facilities_found: "के लिए मिली सुविधाएं",
    scanning_network: "नेटवर्क स्कैन हो रहा है...",
    no_facilities_found: "इस क्षेत्र में कोई सुविधाएं नहीं मिलीं।",
    total_bed_capacity: "कुल बिस्तर क्षमता",
    recent_alerts: "हाल के अलर्ट",
    warnings: "चेतावनियाँ",
    none_active: "कोई सक्रिय नहीं।",
    ambulance_dispatch: "एम्बुलेंस प्रेषण",
    vehicle_identifier: "वाहन पहचानकर्ता",
    operational_status: "परिचालन स्थिति",
    fuel_level: "ईंधन स्तर",
    driver_contact: "ड्राइवर संपर्क",
    live_tracking: "लाइव ट्रैकिंग",
    mock_gps: "मॉक जीपीएस निर्देशांक",
    project_roadmap: "प्रोजेक्ट रोडमैप",
    vision_title: "आरोग्यनेट: भविष्य का रोडमैप",
    vision_subtitle: "जिला स्वास्थ्य कमान के भविष्य में आपका स्वागत है।",
    phase_1: "चरण 1: रीयल-टाइम कमांड",
    phase_1_desc: "आरोग्यनेट वर्तमान में रीयल-टाइम लॉजिस्टिक्स, एआई-संचालित भविष्य कहनेवाला पुनर्वितरण और एक खुला कमांड सेंटर प्रदान करता है।",
    phase_2: "चरण 2: IoT और लाइव सेंसर एकीकरण",
    phase_2_desc: "स्वचालित इन्वेंटरी पिंग और रीयल-टाइम तापमान सेंसर के साथ कोल्ड चेन ट्रैकिंग।",
    phase_3: "चरण 3: ड्रोन डिलीवरी नेटवर्क",
    phase_3_desc: "कमांड सेंटर से सीधे भेजे गए महत्वपूर्ण आपूर्ति ले जाने वाले स्वायत्त ड्रोन।",
    phase_4: "चरण 4: ब्लॉकचेन और विकेन्द्रीकृत पहचान",
    phase_4_desc: "रोगी के इतिहास के लिए सुरक्षित, अपरिवर्तनीय खाता बही और फार्मास्यूटिकल्स का क्रिप्टोग्राफिक सत्यापन।",
    recent_pathogen_logs: "हाल के रोगजनक लॉग",
    operating_status: "परिचालन स्थिति",
    fully_operational: "पूर्णतः चालू",
    public_bed_capacity: "सार्वजनिक बिस्तर क्षमता",
    ambulance_fleet_status: "एम्बुलेंस बेड़े की स्थिति",
    active: "सक्रिय",
    beds: "बिस्तर",
    restricted_message: "विस्तृत रसद और कर्मचारियों की उपस्थिति जिला प्रशासकों तक ही सीमित है।",
    no_recent_disease_logs: "कोई हालिया रोग लॉग नहीं।",
    status: "स्थिति",
    staff_shortage: "कर्मचारी कमी",
    normal: "सामान्य",
    elevated: "बढ़ा हुआ",
    national_overview: "राष्ट्रीय अवलोकन",
    state_insights: "राज्य अंतर्दृष्टि",
    district_explorer: "ज़िला एक्सप्लोरर",
    india_health_infrastructure: "भारत स्वास्थ्य बुनियादी ढांचा",
    real_time_aggregated_data: "भारत सरकार के डेटासेट से रीयल-टाइम एकत्रित डेटा",
    primary_health_centres: "प्राथमिक स्वास्थ्य केंद्र",
    community_health_centres: "सामुदायिक स्वास्थ्य केंद्र",
    govt_doctors: "सरकारी डॉक्टर",
    licensed_blood_banks: "लाइसेंस प्राप्त ब्लड बैंक",
    infrastructure_breakdown: "अवसंरचना विवरण",
    top_states_phcs: "PHC द्वारा शीर्ष राज्य",
    top_states_doctors: "डॉक्टरों द्वारा शीर्ष राज्य",
    top_states_blood_banks: "ब्लड बैंक द्वारा शीर्ष राज्य",
    state_col: "राज्य",
    public_banks: "सार्वजनिक बैंक",
    private_banks: "निजी बैंक",
    total: "कुल",
    state_health_infrastructure: "राज्य स्वास्थ्य अवसंरचना",
    select_state_map: "विस्तृत जानकारी देखने के लिए मानचित्र पर किसी राज्य का चयन करें",
    select_state_dropdown: "जानकारी देखने के लिए एक राज्य चुनें",
    profile: "प्रोफ़ाइल",
    state_workforce: "राज्य कार्यबल",
    sanctioned_doctors: "स्वीकृत डॉक्टर",
    in_position: "कार्यरत",
    shortfall: "कमी",
    district_infrastructure: "जिला अवसंरचना वितरण",
    district: "जिला",
    awaiting_selection: "चयन की प्रतीक्षा है। मानचित्र पर किसी भी राज्य पर क्लिक करें।",
    // Public Portal New Strings
    home: "होम",
    national_data: "राष्ट्रीय डेटा",
    command_login: "कमांड लॉगिन",
    emergency_sos: "आपातकालीन SOS",
    switch_hindi: "हिंदी में बदलें",
    switch_english: "अंग्रेजी में बदलें",
    system_status: "सिस्टम स्थिति: सभी सिस्टम चालू हैं",
    built_for_india: "भारत के लिए निर्मित।",
    
    hero_badge: "आधिकारिक सार्वजनिक पोर्टल",
    hero_title1: "भारत का एआई-संचालित",
    hero_title2: "स्वास्थ्य खुफिया",
    hero_desc: "डेटा और कार्रवाई के बीच की खाई को पाटना। आरोग्यनेट एआई रीयल-टाइम अंतर्दृष्टि, भविष्य कहनेवाला संसाधन आवंटन और नागरिक-प्रथम पारदर्शिता प्रदान करने के लिए राष्ट्रीय डेटासेट को एकीकृत करता है।",
    explore_data: "राष्ट्रीय डेटा देखें",
    
    why_title: "आरोग्यनेट एआई क्यों?",
    why_desc: "दशकों से, स्वास्थ्य डेटा हजारों जिलों में बिखरा हुआ है। आरोग्यनेट एआई एक केंद्रीय तंत्रिका तंत्र के रूप में कार्य करता है, जो बुनियादी ढांचे, कार्यबल और महत्वपूर्ण संसाधनों को पूर्ण दृश्यता प्रदान करता है।",
    unified_data: "एकीकृत डेटासेट",
    unified_data_desc: "ओपन गवर्नमेंट डेटा (ओजीडी) को एकल, उच्च-प्रदर्शन पोस्टग्रेएसक्यूएल इंटेलिजेंस लेयर में एकत्रित करना।",
    pred_analytics: "भविष्य कहनेवाला विश्लेषिकी",
    pred_analytics_desc: "उन्नत एआई मॉडल का उपयोग करके दवा की कमी और बुनियादी ढांचे की बाधाओं का पूर्वानुमान लगाना।",
    cit_transparency: "नागरिक पारदर्शिता",
    cit_transparency_desc: "आम नागरिकों को आस-पास की सुविधाओं, ब्लड बैंक और विशेषज्ञ डॉक्टरों का पता लगाने के लिए सशक्त बनाना।",
    
    dual_intel: "दोहरी-लक्षित खुफिया",
    for_citizens: "नागरिकों के लिए",
    cit_point1: "निकटतम चालू पीएचसी और सीएचसी का पता लगाएं",
    cit_point2: "लाइसेंस प्राप्त ब्लड बैंकों की रीयल-टाइम उपलब्धता की जांच करें",
    cit_point3: "अपने राज्य में विशेष डॉक्टर की उपलब्धता देखें",
    cit_point4: "रोग सलाह और आपातकालीन एसओएस तक पहुंचें",
    view_dashboard: "सार्वजनिक डैशबोर्ड देखें",
    // Contact Page
    contact_title: "संपर्क",
    contact_desc: "प्लेटफॉर्म, डेटासेट या एकीकरण के बारे में प्रश्न हैं? हमारी टीम से संपर्क करें।",
    contact_form_title: "हमें एक संदेश भेजें",
    contact_success: "संदेश सफलतापूर्वक भेजा गया। हमारी टीम जल्द ही आपसे संपर्क करेगी।",
    contact_error: "संदेश भेजने में विफल। कृपया बाद में पुनः प्रयास करें।",
    contact_signin_msg: "सुझाव भेजने या टीम से संपर्क करने के लिए कृपया साइन इन करें।",
    contact_signin_btn: "साइन इन करें",
    contact_name: "नाम",
    contact_email: "ईमेल",
    contact_phone: "फ़ोन नंबर",
    contact_subject: "विषय",
    contact_message: "संदेश",
    contact_send_btn: "संदेश भेजें",
    contact_founder: "संस्थापक",
    contact_founder_desc: "भारत के लिए एआई-संचालित स्वास्थ्य सेवा खुफिया समाधान का निर्माण। सहयोग में रुचि रखते हैं? सहयोग के लिए संपर्क करें।",
    contact_linkedin: "लिंक्डइन पर जुड़ें",
    
    // District Explorer
    explore_healthcare: "अपने आस-पास स्वास्थ्य देखभाल बुनियादी ढांचे का अन्वेषण करें",
    search_district: "अपना जिला खोजें...",
    featured_districts: "चुनिंदा जिले",
    search_results: "खोज परिणाम",
    no_districts_found: "कोई जिला नहीं मिला।",
    district_profile: "स्वास्थ्य बुनियादी ढांचा प्रोफ़ाइल",
    back_to_districts: "जिलों पर वापस जाएँ",
    infrastructure_distribution: "बुनियादी ढांचा वितरण",

    for_govt: "सरकार के लिए",
    gov_point1: "राज्य-वार ऐतिहासिक विकास प्रवृत्तियों का विश्लेषण करें",
    gov_point2: "रीयल-टाइम इन्वेंट्री और लॉजिस्टिक्स की निगरानी करें",
    gov_point3: "निगरानी मॉड्यूल के माध्यम से बीमारी के प्रकोप को ट्रैक करें",
    gov_point4: "एआई-संचालित कर्मचारियों की उपस्थिति और फुटप्रिंट की भविष्यवाणी",
    access_command: "कमांड सेंटर तक पहुंचें",
    
    future_roadmap: "राष्ट्रीय विस्तार रोडमैप",
    future_roadmap_desc: "हम अपनी खुफिया क्षमताओं का विस्तार करने के लिए बड़े पैमाने पर केंद्रीय डेटासेट को सक्रिय रूप से एकीकृत कर रहे हैं।",
    coming_phase2: "चरण 2 आ रहा है",
    aqi_heatwave: "एक्यूआई और हीटवेव अलर्ट",
    maternal_child: "मातृ एवं शिशु स्वास्थ्य",
    vaccination_intel: "टीकाकरण खुफिया",
    census_pop: "जनगणना और जनसंख्या",

  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // 'en' or 'hi'

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
